# Generated by Django 5.2 on 2025-07-14 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
        ('estoque', '0002_alter_produtos_options_alter_venda_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracao.vendedor'),
        ),
    ]
