# Generated by Django 5.2 on 2025-07-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_venda_total_alter_venda_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='quantidade',
            field=models.FloatField(default=0),
        ),
    ]
