# Generated by Django 5.2 on 2025-08-07 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_venda_cancelada_alter_produtos_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.venda'),
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
