# Generated by Django 5.1.3 on 2024-12-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administracao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="idade",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
