# Generated by Django 5.1.3 on 2024-12-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administracao", "0002_delete_gerente_delete_vendedor_gerente_vendedor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gerente",
            options={"verbose_name": "Gerente"},
        ),
        migrations.AlterModelOptions(
            name="vendedor",
            options={"verbose_name": "Vendedore"},
        ),
        migrations.AlterField(
            model_name="users",
            name="cargo",
            field=models.CharField(
                blank=True,
                choices=[("V", "Vendedor"), ("G", "Gerente")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="nome",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
