# Generated by Django 5.1.3 on 2024-12-09 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administracao", "0002_users_idade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="idade",
        ),
    ]
