# Generated by Django 5.1.3 on 2025-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administracao", "0003_alter_gerente_options_alter_vendedor_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sobrenome", models.CharField(max_length=200)),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, max_length=14, unique=True, verbose_name="CPF"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Telefone"
                    ),
                ),
                ("endereco", models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.AlterModelOptions(
            name="gerente",
            options={"verbose_name": "Gerente", "verbose_name_plural": "Gerentes"},
        ),
        migrations.AlterModelOptions(
            name="vendedor",
            options={"verbose_name": "Vendedor", "verbose_name_plural": "Vendedores"},
        ),
    ]
